import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuList,
} from '@/components/ui/navigation-menu';
import Link from 'next/link';
import {Button} from '@/components/ui/button';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
      <html lang="en">
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="mt-12 flex items-center justify-center">
        <NavigationMenu>
          <NavigationMenuList>
            <NavigationMenuItem className="space-x-4">
              <Link href="/posts">
                <Button variant="link"
                        className="cursor-pointer">Posts</Button>
              </Link>
              <Link href="/preview">
                <Button variant="link"
                        className="cursor-pointer">Preview</Button>
              </Link>
            </NavigationMenuItem>
          </NavigationMenuList>
        </NavigationMenu>
      </div>
      <div
          className="font-sans items-center justify-items-center p-8 pb-20 gap-16 sm:p-20">

        {children}
      </div>
      </body>
      </html>
  );
}
